- .github/workflows/release.yml
- .gitignore
- commitlint.config.js
- package-lock.json
- package.json
> ci: 🎡 added release versioning and github workflow

- nginx/conf/nginx.conf
Fixes #2 
adjusted the default Nginx configuration to improve security again denial of service attacks
> Feature nginx dos

- nginx/conf/locations/rocketchat.conf
> Feature rocketchat cors header

- nginx/conf/locations/keycloak.conf
- nginx/conf/locations/rocketchat.conf
- nginx/conf/nginx.conf
> feat: added whitelist for rocketchat and keycloak api

- nginx/conf/locations/rocketchat.conf
Added missing file download path to whitelist
> fix: added missing file download path to whitelist

- nginx/conf/locations/rocketchat.conf
Added rate limiting for Rocket.Chat websocket and file upload calls.
> Feature rate limit adjustments

- nginx/conf/locations/liveservice.conf
> feat: added upgrade headers needed for websocket connection

- MessageService/MessageService.env
> feat: add messageservice properties

- .github/workflows/release.yml
> feat: restrict release action to branches starting with release

- nginx/conf/locations/rocketchat.conf
> feat: increment rate limit for subscription.read call

- docker-compose.yml
> Feature update openldap

- docker-compose.yml
- mongoDB/init-oplog-user.js
- mongoDB/init-replica-set.js
- mongoDB/init-rocketchat-user.js
Updates MongoDB and Rocket.Chat to latest versions
> feat: update versions of rocket.chat and mongodb

- Rocket.Chat/Rocket.Chat.env
Added mongodb oplog connection url
> chore: added mongodb oplog connection url

- nginx/conf/locations/agencyservice.conf
> feat: integrate agency admin service path

- nginx/conf/locations/userservice.conf
> feat: integrate userservice admin service path

- docker-compose.yml
Added missing volume mappings.
> chore: added missing volume mappings

- docker-compose.yml
> chore: added missing temp volume

- nginx/conf/security-headers.conf
Added X-Reason access control expose header
> feat: add x-reason access control expose header

- nginx/conf/nginx.conf
Added tls version to nginx access log
> feat added tsl version to nginx access log

- nginx/conf/locations/rocketchat.conf
- nginx/conf/nginx.conf
> feat: user nginx cors configuration for rocket chat rest api

- docker-compose.yml
> feat: add volume for violation reports

- nginx/conf/locations/supportgroupvechta.conf
> feat: add registration location for support group vechta

- Keycloak/logging/standalone-ha.xml
- docker-compose.yml
> feat: exclude ip address in keycloak logging

- Keycloak/logging/standalone-ha.xml
> feat: add regex pattern for brutforce log message

- nginx/conf/custom-error-logging.conf
- nginx/conf/server/server-default.conf
> feat: include custom error logging

- nginx/conf/server/server-default.conf
Added redirects for general ip address access, e.g. Keycloak
> chore: added redirects for general ip address access

- nginx/conf/locations/userservice.conf
> feat: add location for conversations api

- Keycloak/logging/standalone-ha.xml
- docker-compose.yml
- package-lock.json
- package.json
> feat: update open source components

- Keycloak/caritas-theme/login/info.ftl
- Keycloak/caritas-theme/login/login-reset-password.ftl
- Keycloak/caritas-theme/login/login.ftl
- Keycloak/caritas-theme/login/messages/messages_de.properties
- Keycloak/caritas-theme/login/resources/css/caritas.css
- nginx/conf/locations/keycloak.conf
> fix: adapt templates to match new wildfly version

- nginx/conf/locations/keycloak.conf
Fixes 403 forbidden on password reset process
> fix: fixes 403 forbidden on password reset process

- Keycloak/realm-export.json
> feat: update keycloak realm export

- Keycloak/diakonie-theme/login/login-reset-password.ftl
> fixed login link on password reset

- nginx/conf/locations/keycloak.conf
from ‘caritas-online-beratung’ to ‘online-beratung’
Fixes #
-
-
-
> refactor changed realm name

- Keycloak/caritas-theme/email/html/otp-email.ftl
- Keycloak/caritas-theme/email/messages/messages_de.properties
- Keycloak/caritas-theme/email/messages/messages_en.properties
- Keycloak/caritas-theme/email/text/otp-email.ftl
> feat: support multi-language email templates
